config/routes.rb
Supertravel::Application.routes.draw do
  resources :contacts

  resources :tasks

  get "plans/add_event"
  get "plans/remove_event"

  get "opinions/destroy"

  get "search/results"
  get "static/index"
  get "static/about"
  get "static/contact"

  resources :plans

  resources :events do
    resources :opinions
  end

  devise_for :users do
    resources :plans
  end

  root :to => 'static#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :opinions
  validates_uniqueness_of :api_id
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= Eventful::get_event(@event.api_id)['description'].html_safe %>
</p>

<h2>opinions</h2>
<% @event.opinions.each do |opinion| %>
    <p>
      <b>opinion:</b>
      <%= opinion.text %>
    </p>
    <% if opinion.commenter == current_user.id %>
    <%= link_to 'Destroy', '/opinions/destroy?event_id=' + @event.id.to_s + '&opinion_id=' + opinion.id.to_s %>
    <% end %>
<% end %>

<h2>Add a opinion:</h2>
<%= form_for([@event, @event.opinions.build]) do |f| %>
    <div class="field">
      <%= f.label :text %>
      <br/>
      <%= f.text_area :text %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

<br/>

<%= link_to 'Edit event', edit_event_path(@event) %>
<%= link_to 'Back to events', events_path %>