config/routes.rb
Supertravel::Application.routes.draw do
  resources :contacts

  resources :tasks

  get "plans/add_event"
  get "plans/remove_event"

  get "opinions/destroy"

  get "search/results"
  get "static/index"
  get "static/about"
  get "static/contact"

  resources :plans

  resources :events do
    resources :opinions
  end

  devise_for :users do
    resources :plans
  end

  root :to => 'static#index'

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  belongs_to :user
  serialize :events, Array
  validates_uniqueness_of :name

  def add_event(api_id)
    new_array = self.events.push(api_id.to_s)
    update_attribute :events, new_array
  end

  def remove_event(api_id)
    array = self.events
    array.delete(api_id)
    update_attribute :events, array
  end

end

app/controllers/plans_controller.rb
require 'wunderground'
require 'mail'
class PlansController < ApplicationController

  before_filter :authenticate_user!

  # GET /plans
  # GET /plans.json
  def index
    @plans = current_user.plans

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @plans }
    end
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
    @plan = Plan.find(params[:id])

    w = Wunderground.new('bef26a2b0f485846')
    @forecast = w.forecast_for(@plan.city.gsub(' ', '_'))

    if params['email'] != nil
      emailAd = params['email']
      subjectP = 'Itinerario del viaje ' + @plan.name.to_s
      options = {:address => "smtp.gmail.com",
                 :port => 587,
                 :user_name => 'noreply.supertravel@gmail.com',
                 :password => 'Hola1234',
                 :authentication => 'plain',
                 :enable_starttls_auto => true}
      bodyP = current_user.email + " te envia su itinerario para el viaje " + @plan.name.to_s + "\n"
      @plan.events.each do |event|
        bodyP += (Eventful.get_event(event)['title'] + "\n")
      end

      Mail.deliver do
        to emailAd
        from 'noreply.supertravel@gmail.com'
        subject subjectP
        body bodyP
        delivery_method :smtp, options
      end
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @plan }
      format.pdf {
        html = render_to_string(:layout => 'pdf.html.erb', :action => 'show.html.erb', :formats => [:html], :handler => [:erb])
        kit = PDFKit.new(html)
        kit.stylesheets << "#{Rails.root.to_s}/app/assets/stylesheets/application.css"
        send_data(kit.to_pdf, :filename => "#{@plan.name.gsub(' ', '')}.pdf", :type => 'application/pdf')
        return # to avoid double render call
      }
    end
  end

  # GET /plans/new
  # GET /plans/new.json
  def new
    @plan = Plan.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @plan }
    end
  end

  # GET /plans/1/edit
  def edit
    @plan = Plan.find(params[:id])
  end

  # POST /plans
  # POST /plans.json
  def create
    params[:plan]["user"] = current_user
    @plan = Plan.new(params[:plan])

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render json: @plan, status: :created, location: @plan }
      else
        format.html { render action: "new" }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /plans/1
  # PUT /plans/1.json
  def update
    @plan = Plan.find(params[:id])

    respond_to do |format|
      if @plan.update_attributes(params[:plan])
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy

    respond_to do |format|
      format.html { redirect_to plans_url }
      format.json { head :no_content }
    end
  end

  def add_event
    @plan = Plan.find(params[:id])
    event = Event.create(:api_id => params[:event_id])
    @plan.add_event(event.api_id)

    respond_to do |format|
      format.html { redirect_to '/plans/' + params[:id] }
      format.json { head :no_content }
    end
  end

  def remove_event
    @plan = Plan.find(params[:id])
    @plan.remove_event(params[:event_id])

    respond_to do |format|
      format.html { redirect_to '/plans/' + params[:id] }
      format.json { head :no_content }
    end
  end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<%= form_for(@plan) do |f| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% @plan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :starts_on %><br />
    <%= f.date_select :starts_on %>
  </div>
  <div class="field">
    <%= f.label :ends_on %><br />
    <%= f.date_select :ends_on %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plans/edit.html.erb
<h1>Editing plan</h1>

<%= render 'form' %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
<div class="row map-row" id="map"><br></div>

<div class="row" id="thediv">
  <table class="table table-striped">
    <tr>
      <!--    <th>User</th> -->
      <th>Name</th>
      <th>Description</th>
      <th>Starts on</th>
      <th>Ends on</th>
      <th></th>
      <th></th>
    </tr>

    <% @plans.each do |plan| %>
        <tr onmouseover="geocoder.query('<%= plan.city %>', showOnMap);">
          <td><%= link_to plan.name, 'plans/' + plan.id.to_s %></td>
          <td><%= plan.description %></td>
          <td><%= plan.starts_on %></td>
          <td><%= plan.ends_on %></td>
          <td><%= link_to 'Edit', edit_plan_path(plan) %></td>
          <td><%= link_to 'Destroy', plan, confirm: 'Are you sure?', method: :delete %></td>
        </tr>
    <% end %>
  </table>
</div>

<br>

<script>
    var map = L.mapbox.map('map', 'jsrolon554.map-u7uovq21',  {
        center: [51.505, -0.09],
        zoom: 4
    });
    var geocoder = L.mapbox.geocoder('jsrolon554.map-u7uovq21');

    <% @plans.each do |plan| %>
    geocoder.query('<%= plan.city %>', addMarker);
    <% end %>

    function addMarker(err, data) {
        L.mapbox.markerLayer({
            // this feature is in the GeoJSON format: see geojson.org
            // for the full specification
            type: 'Feature',
            geometry: {
                type: 'Point',
                // coordinates here are in longitude, latitude order because
                // x, y is the standard for GeoJSON and many formats
                coordinates: data.latlng.reverse()
            }
        }).addTo(map);
    };

    function showOnMap(err, data) {
        map.setView(data.latlng, 4);
    };
</script>


<%= link_to 'New Plan', new_plan_path %>

app/views/plans/new.html.erb
<h0>New plan</h0>

<%= render 'form' %>

<%= link_to 'Back', plans_path %>

app/views/plans/show.html.erb
<% require 'wunderground' %>

<p id="notice"><%= notice %></p>

<div id="timeline-embed"></div><br><br>

<div class="well">
  <table>
    <p>
      <b>User:</b>
      <%= @plan.user.email %>
    </p>

    <p>
      <b>Description:</b>
      <%= @plan.description %>
    </p>

    <p>
      <b>Name:</b>
      <%= @plan.name %>
    </p>

    <p>
      <b>Starts on:</b>
      <%= @plan.starts_on %>
    </p>

    <p>
      <b>Ends on:</b>
      <%= @plan.ends_on %>
    </p>

    <p>
      <b>Weather:</b>
      <% if @forecast["response"]["results"].nil? %>
          <% city=@forecast['forecast']['txt_forecast']['forecastday'][0] %>
          <%= image_tag(city['icon_url']) %>
          <%= city['fcttext'] %>
      <% else %>
          <% w = Wunderground.new('bef26a2b0f485846') %>
          <% city=w.forecast_for(@forecast["response"]["results"][0]['zmw'])['forecast']['txt_forecast']['forecastday'][0] %>
          <%= image_tag(city['icon_url']) %>
          <%= city['fcttext'] %>
      <% end %>
    </p>

    <p>
      <b>List of attached Events:</b><br>
      <% @plan.events.each do |event| %>
          <%= link_to Eventful.get_event(event)['title'], '/events/' + Event.find_by_api_id(event).id.to_s %>
          <%= link_to 'Destroy', '/plans/remove_event?id=' + @plan.id.to_s + '&event_id=' + event %>
          <br>
      <% end %>
    </p>
  </table>
  <%= link_to 'Search for events to add', '/search/results?q=' + @plan.city.to_s %>
  <br>
  <%= link_to 'Download PDF', plan_path(@plan, :format => 'pdf') %>
</div>

<div class='well'>
  Compartir itinerario por email<br><br>
  <form action="<%= @plan.id.to_s %>" method="get">
    <input type="text" id="email" name="email">
    <button class="btn" type="submit">Enviar</button>
  </form>
</div>

<script type="text/javascript">

  var data = {
      "timeline":
      {
          "headline":"<%= @plan.name %>",
          "type":"default",
          "text":"<p><%= @plan.description %></p>",
          "date": [
              <% @plan.events.each do |event| %>
              {
                  "startDate":"<%= Eventful.get_event(event)['start_time'] %>",
                  "endDate":"<%= Eventful.get_event(event)['stop_time'] %>",
                  "headline":"<%= Eventful.get_event(event)['title'] %>",
                  "text":"Prueba"
              },
              <% end %>
          ]
      }
  };

    createStoryJS({
        width:      '100%',
        height:     '600',
        css: '/assets/stylesheets/timeline.css',
        source: data,
        js: '/assets/javascripts/timeline.js',
        embed_id:   'timeline-embed'
    });
</script>